---
title: "FEP Comparison Tables"
author: "Sarah Gaichas"
date: "`r Sys.Date()`"
output:
  html_document:
    code_fold: hide
    toc: true
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
```

# Summarize pdfs with Claude API

I used code in this project [R/pdfsumm.R](https://github.com/sgaichas/SAFMCindicators/blob/main/R/pdfsumm.R). Code is reproduced in this code block but is not run here.

```{r pdfsumm, file='https://github.com/sgaichas/SAFMCindicators/raw/main/R/pdfsumm.R', eval=FALSE}

```


# Knit all of the Claude summaries

```{r, eval=FALSE}
# knit all rmd in a directory

fepsumms <- list.files(here::here("FEPsumms"), pattern = "\\.Rmd$", full.names = TRUE)

#knitone

knitone <- function(fpath) {
  file_name <- tools::file_path_sans_ext(basename(fpath))
  outdir <- dirname(fpath)
  # Define the output file path for the PDF
  output_file <- file.path(outdir, paste0(file_name, ".pdf"))
  
  # Render the Rmd file to PDF
  # output_format: specifies PDF output
  # output_file: specifies the name and location of the output PDF
  # output_dir: specifies the directory where the output will be saved
  rmarkdown::render(input = fpath, 
                    output_format = "pdf_document", 
                    output_file = output_file,
                    output_dir = outdir)
  
}

purrr::map(fepsumms, knitone)



```

# Now tell Claude to compare objectives across docs in a table
